stages:
  - build
  - deploy
before_script:
  - 'cd /var/www/html/frontend'
  - git pull origin develop

npm_install:
  stage: build
  tags:
    - gipam-front
  script:
    - npm install --ignore-scripts
  only:
    - develop
frontend_build:
  stage: deploy
  tags:
    - gipam-front
  script:
    - ng build --configuration=recette --baseHref=/frontend/
  only:
    - develop
variables:
  GIT_STRATEGY: none
