import { Injectable } from '@angular/core';
import { TreeviewItem } from 'ngx-treeview';

@Injectable({
  providedIn: 'root',
})
export class WorkOfArtService {
  domaine = [
    {
      id: 0,
      name: 'Art graphique',
      denominations: [
        { id: 1, name: 'Affiche' },
        { id: 2, name: 'Dessin' },
        { id: 3, name: 'Estampe' },
        { id: 4, name: 'Gravure' },
        { id: 5, name: 'Peinture sur papier' },
        { id: 6, name: 'Photographie' },
      ],
    },
    {
      id: 1,
      name: 'Horlogerie',
      denominations: [
        { id: 1, name: 'Horloge' },
        { id: 2, name: 'Pendule' },
        { id: 3, name: 'Régulateur' },
      ],
    },
    {
      id: 2,
      name: 'Luminaire',
      denominations: [
        { id: 1, name: 'Applique' },
        { id: 2, name: 'Chandelier' },
      ],
    },
    { id: 4, name: 'Object décoratif' },
    { id: 5, name: 'Peinture' },
    {
      id: 6,
      name: 'Sculpture',
      denominations: [
        { id: 1, name: 'Buste' },
        { id: 2, name: 'Relief' },
      ],
    },
    { id: 7, name: 'Art textile' },
    { id: 8, name: 'Pièce de musée' },
    { id: 9, name: 'Art de la table' },
    { id: 10, name: 'Decor monumental' },
    { id: 11, name: 'Archeologie' },
  ];
  denominations = [
    { id: 1, name: 'Affiche' },
    { id: 2, name: 'Dessin' },
    { id: 3, name: 'Estampe' },
    { id: 4, name: 'Gravure' },
    { id: 5, name: 'Peinture sur papier' },
    { id: 6, name: 'Photographie' },
    { id: 7, name: 'Horloge' },
    { id: 8, name: 'Pendule' },
    { id: 9, name: 'Régulateur' },
    { id: 10, name: 'Art textile' },
    { id: 11, name: 'Pièce de musée' },
    { id: 12, name: 'Art de la table' },
    { id: 13, name: 'Decor monumental' },
    { id: 14, name: 'Archeologie' },
  ];
  epoque = [
    { id: 0, name: 'Renaissance' },
    { id: 1, name: 'XVIIe siècle' },
    { id: 2, name: 'Empire' },
    { id: 3, name: 'Restauration' },
    { id: 4, name: 'Second Empire' },
    { id: 5, name: 'Louis Philippe' },
    { id: 6, name: 'Louis XIV' },
    { id: 7, name: 'Louis XV' },
    { id: 8, name: 'Régence' },
    { id: 9, name: 'Directoire' },
    { id: 10, name: 'XVIe siècle' },
    { id: 11, name: 'XIXe siècle' },
    { id: 12, name: 'Paléolithique' },
    { id: 13, name: 'Louis XVIII' },
  ];
  property: string[] = ['Propriété', 'Dépôt'];
  style: string[] = [
    'Baroque',
    'Rustique',
    'Néanderthal',
    'Empire',
    'Art Déco',
    'Louis XV',
    'Directoire',
    'Régence',
    'Restauration',
    'Napoléan III',
    'Transition',
    'Louis-Philippe',
    'Charles X',
    'Louis XIV',
    'Oriental',
    'Chinois',
    'Contemporain',
  ];
  ministeres = [
    { id: 0, name: 'MINISTÈRES ÉCONOMIQUES ET FINANCIERS' },
    { id: 1, name: 'MINISTÈRE DU COMMERCE EXTÉRIEUR' },
    { id: 2, name: "SECRÉTARIAT D'ÉTAT CHARGE DU BUDGET" },
    { id: 3, name: "MINISTÈRE DÉLÉGUÉ A L'INDUSTRIE" },
    { id: 4, name: "SECRETARIAT D'ETAT CHARGÉ DE LA FONCTION PUBLIQUE" },
    { id: 5, name: 'Louis Philippe' },
    { id: 6, name: "SECRÉTARIAT D'ETAT CHARGÉ DU COMMERCE EXTÈRIEUR" },
    { id: 7, name: "SECRÉTARIAT D'ÉTAT CHARGÉ DE L'EMPLOI" },
    {
      id: 8,
      name:
        "SECRÉTARIAT D'ÉTAT CHARGÉ COMMERCE, DE L'ARTISANAT, DES PME, DU TOURISME, DES SERVICES, DES PROFESSIONS LIBERALES ET DE LA CONSOMMATION",
    },
    { id: 9, name: "MINISTÈRE DE L'ARTISANAT, DU COMMERCE  ET DU TOURISME" },
    { id: 10, name: "SECRÉTARIAT D'ETAT CHARGÉ DU NUMÉRIQUE" },
    { id: 11, name: 'MINISTÈRE DE LA FONCTION PUBLIQUE' },
  ];
  authors = [
    { id: 0, name: 'author 1' },
    { id: 1, name: 'author 2' },
    { id: 2, name: 'author 3' },
    { id: 3, name: 'author 4' },
    { id: 4, name: 'author 5' },
    { id: 5, name: 'author 6' },
    { id: 6, name: 'author 7' },
  ];
  proofs = [
    {
      id: 0,
      titre: 'titre 1',
      creationDate: '04/12/2020',
      nombre_prood_a_recole: '5',
      nombre_prood_recole: '15',
      created_by: 'Test',
      minister: 'MINISTÈRES ÉCONOMIQUES ET FINANCIERS',
      etab: 'Secrétariat Général des Ministères Économique et Financier',
      service: "Service de l'Environnement Professionnel 2B",
    },
    {
      id: 1,
      titre: 'titre 2',
      creationDate: '19/10/2020',
      nombre_prood_a_recole: '5',
      nombre_prood_recole: '15',
      created_by: 'Test',
      minister: 'MINISTÈRES ÉCONOMIQUES ET FINANCIERS',
      etab: 'Secrétariat Général des Ministères Économique et Financier',
      service: "Service de l'Environnement Professionnel 2B",
    },
    {
      id: 2,
      titre: 'titre 3',
      creationDate: '04/12/2020',
      nombre_prood_a_recole: '5',
      nombre_prood_recole: '15',
      created_by: 'Test',
      minister: 'MINISTÈRES ÉCONOMIQUES ET FINANCIERS',
      etab: 'Secrétariat Général des Ministères Économique et Financier',
      service: "Service de l'Environnement Professionnel 2B",
    },
    {
      id: 3,
      titre: 'titre 4',
      creationDate: '04/12/2020',
      nombre_prood_a_recole: '5',
      nombre_prood_recole: '15',
      created_by: 'Test',
      minister: 'MINISTÈRES ÉCONOMIQUES ET FINANCIERS',
      etab: 'Secrétariat Général des Ministères Économique et Financier',
      service: "Service de l'Environnement Professionnel 2B",
    },
  ];
  proofsDetails = [
    {
      proofId: 0,
      id: 0,
      inventaire: 103,
      Titre: 'titre 1',
      Domaine: 'Couverts',
      Denomination: 'Statuette',
      Auteur: 'auteur',
      Total_recole: '10',
      Date_last_recole: '04/03/2021',
      Recole: true,
    },
    {
      proofId: 0,
      id: 1,
      inventaire: 104,
      Titre: 'titre 1',
      Domaine: 'Couverts',
      Denomination: 'Statuette',
      Auteur: 'auteur',
      Total_recole: '10',
      Date_last_recole: '04/03/2021',
      Recole: false,
    },
    {
      proofId: 0,
      id: 2,
      inventaire: 105,
      Titre: 'titre 1',
      Domaine: 'Couverts',
      Denomination: 'Statuette',
      Auteur: 'auteur',
      Total_recole: '10',
      Date_last_recole: '05/03/2021',
      Recole: true,
    },
    {
      proofId: 1,
      id: 0,
      inventaire: 106,
      Titre: 'titre 1',
      Domaine: 'Couverts',
      Denomination: 'Statuette',
      Auteur: 'auteur',
      Total_recole: '10',
      Date_last_recole: '04/03/2021',
      Recole: true,
    },
    {
      proofId: 1,
      id: 1,
      inventaire: 107,
      Titre: 'titre 1',
      Domaine: 'Couverts',
      Denomination: 'Statuette',
      Auteur: 'auteur',
      Total_recole: '10',
      Date_last_recole: '04/03/2021',
      Recole: false,
    },
    {
      proofId: 1,
      id: 2,
      inventaire: 108,
      Titre: 'titre 1',
      Domaine: 'Couverts',
      Denomination: 'Statuette',
      Auteur: 'auteur',
      Total_recole: '10',
      Date_last_recole: '05/03/2021',
      Recole: true,
    },
    {
      proofId: 1,
      id: 3,
      inventaire: 109,
      titre: 'titre 1',
      Domaine: 'Couverts',
      Denomination: 'Statuette',
      Auteur: 'auteur',
      total_recole: '10',
      Date_last_recole: '05/03/2021',
      Recole: true,
    },
  ];
  alerts = [
    {
      reference: 'Réf 145',
      date: '01/01/2021',
      auteur: 'Auteur1;Auteur2',
      titre: 'titre1',
      actiontype: 'En recherche',
      startDate: '31/10/2020',
      endDate: '31/12/2020',
      delai: '62',
      status: 'en cours',
      createdBy: 'Test',
    },
    {
      reference: 'Réf 365',
      date: '01/07/2021',
      auteur: 'Auteur54',
      titre: 'titre2',
      actiontype: 'Dépot de plainte',
      startDate: '12/05/2020',
      endDate: '30/06/2020',
      delai: '62',
      status: 'en cours',
      createdBy: 'Test',
    },
    {
      reference: 'Réf 478',
      date: '29/11/2020',
      auteur: 'Auteur1',
      titre: 'titre5',
      actiontype: 'Déclassement',
      startDate: '31/10/2020',
      endDate: '28/11/2020',
      delai: '62',
      status: 'en cours',
      createdBy: 'Test',
    },
    {
      reference: 'Réf 587',
      date: '01/01/2021',
      auteur: 'Auteur6',
      titre: 'titre458',
      actiontype: 'En attente de localisation',
      startDate: '31/10/2020',
      endDate: '31/12/2020',
      delai: '62',
      status: 'en cours',
      createdBy: 'Test',
    },
  ];
  oeuvres = [
    {
      id: 0,
      titre: 'Vénus de Milo',
      auteur: 'auteur',
      denomination: 'Statuette',
      description: 'Une statue en marbre représentantla déesse Aphrodite-C.',
      mots_descriptifs: 'mots_descriptifs',
      commentaire: 'commentaire',
      image: 'assets/images/573.jpg',
      vip: 'true',
      domaine: 'Sculpture',
      editeur: "Alexandros d'Antioche",
      anneeCreation: 1820,
      dimension: '202x36x64',
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '12/07/1985',
      property: 'Propriété',
      visible: true,
    },
    {
      id: 1,
      titre: 'Nature morte',
      denomination: 'Couverts',
      description: 'Le Portrait de Mona Lisa est celui de la Florentine Lisa Gherardini',
      image: 'assets/images/1.jpg',
      vip: 'true',
      status: 'notRecieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1519,
      dimension: '77 × 53 cm',
      style: 'Renaissance',
      matiere: 'Huile sur panneau de bois',
      creationDate: '15/02/1975',
      property: 'Propriété',
      visible: true,
    },
    {
      id: 2,
      titre: 'La Belle Ferronnière',
      denomination: 'Couverts',
      description: 'Un tableau peint sur un panneau en bois de noyer',
      image: 'assets/images/2.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1497,
      dimension: '62 × 44 cm',
      style: 'Renaissance',
      matiere: 'Huile sur panneau de bois',
      creationDate: '30/11/1920',
      property: 'Propriété',
      visible: false,
    },
    {
      id: 3,
      titre: 'La Liberté guidant le peuple',
      denomination: 'Couverts',
      description: "Une huile sur toile d'Eugène Delacroix  ",
      image: 'assets/images/4.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Sculpture',
      editeur: 'Eugène Delacroix',
      anneeCreation: 1830,
      dimension: '260 × 325 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '25/12/1921',
      property: 'Dépôt',
      visible: true,
    },
    {
      id: 4,
      titre: 'ECOLE FRANCAISE VERS 1830,D’APRÈS PIERRE...',
      description: 'ECOLE FRANCAISE VERS 1830, D’APRÈS PIERRE...',
      image: 'assets/images/25.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: '',
      anneeCreation: '',
      dimension: '77 × 53 cm',
      style: 'Tableau non classés',
      creationDate: '24/10/1919',
      property: 'Propriété',
      visible: false,
    },
    {
      id: 5,
      titre: 'Victoire de Samothrace',
      description: "Un monument de sculpture grecque trouvé dans l'île de Samothrace.",
      image: 'assets/images/35.jpg',
      vip: 'false',
      status: 'notRecieved',
      domaine: 'Sculpture',
      anneeCreation: 1863,
      dimension: '77 × 53 cm',
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '30/11/1920',
      property: 'Dépôt',
      visible: true,
    },
    {
      id: 6,
      titre: "L'Esclave mourant",
      auteur: 'auteur',
      description: 'Une statue en marbre représentantla déesse Aphrodite-C.',
      mots_descriptifs: 'mots_descriptifs',
      commentaire: 'commentaire',
      image: 'assets/images/162.JPG',
      vip: 'true',
      domaine: 'Sculpture',
      editeur: 'Michel-Ange',
      anneeCreation: 1820,
      dimension: '202x36x64',
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '27/09/1914',
      property: 'Propriété',
      visible: false,
    },

    {
      id: 7,
      titre: 'La Vierge aux rochers',
      description: 'Considérée par les historiens comme la première des deux versions.',
      image: 'assets/images/0000.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1483,
      dimension: '199 × 122 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '30/11/1920',
      property: 'Dépôt',
      visible: true,
    },
    {
      id: 8,
      titre: 'Les Noces de Cana',
      description: "Une huile sur toile d'Eugène Delacroix  ",
      image: 'assets/images/304.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Paul Véronèse',
      anneeCreation: 1563,
      dimension: '677 × 994 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '19/01/1990',
      property: 'Propriété',
      visible: false,
    },
    {
      id: 9,
      titre: 'Victoire de Samothrace',
      description: "Un monument de sculpture grecque trouvé dans l'île de Samothrace.",
      image: 'assets/images/343 .jpg',
      vip: 'false',
      status: 'notRecieved',
      domaine: 'Sculpture',
      editeur: '',
      anneeCreation: 1863,
      dimension: '77 × 53 cm',
      matiere: 'Marbre',
      style: 'Sculpture',
      creationDate: '30/11/1920',
      property: 'Dépôt',
      visible: true,
    },
    {
      id: 10,
      titre: "Vénus d'Arles",
      description: 'une sculpture en marbre dégagée en 1651',
      image: 'assets/images/365.jpg',
      vip: 'false',
      status: 'notRecieved',
      domaine: 'Sculpture',
      editeur: '',
      dimension: '194 cm (hauteur)',
      anneeCreation: 1651,
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '21/02/1920',
      property: 'Dépôt',
      visible: true,
    },
    {
      id: 11,
      titre: 'Saint Jean-Baptiste',
      description: ' Peint sur une planche de noyer et mesure 69 × 57 cm',
      image: 'assets/images/12.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1516,
      dimension: '69 × 57 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '30/11/1920',
      property: 'Propriété',
      visible: true,
    },
  ];
  getDomains(): TreeviewItem[] {
    return [
      new TreeviewItem({
        text: 'Art textile',
        value: 91,
        collapsed: true,
        children: [
          { text: 'Tapis', value: 9111, checked: false },
          { text: 'Tapisserie', value: 9112, checked: false },
          { text: 'Rideaux', value: 9112, checked: false },
        ],
        checked: false,
      }),
      new TreeviewItem({ text: 'Art graphique', value: 91, checked: false }),
      new TreeviewItem({
        text: 'Horlogerie',
        collapsed: true,
        value: 91,
        children: [
          { text: 'Horloge', value: 9111, checked: false },
          { text: 'Pendule', value: 9112, checked: false },
          { text: 'Régulateur', value: 9112, checked: false },
        ],
        checked: false,
      }),
      new TreeviewItem({
        text: 'Mobilier',
        value: 91,
        collapsed: true,
        children: [
          { text: 'denom 1', value: 9111, checked: false },
          { text: 'denom 2', value: 9112, checked: false },
        ],
        checked: false,
      }),
      new TreeviewItem({ text: 'Luminaire', value: 91, checked: false }),
      new TreeviewItem({ text: 'Object décoratif', value: 91, checked: false }),
      new TreeviewItem({ text: 'Decor monumental', value: 91, checked: false }),
      new TreeviewItem({ text: 'Art de la table', value: 91, checked: false }),
    ];
  }
  constructor() {}
}
