import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class WorkOfArtService {
  domaine: string[] = [
    'Art graphique',
    'Horlogerie',
    'Luminaire',
    'Mobilier',
    'Objet décoratif',
    'Peinture',
    'Sculpture',
    'Art textile',
    'Pièce de musée',
    'Art de la table',
    'Décor monumental',
    'Archeologie',
  ];
  epoque: string[] = [
    'Renaissance',
    'XVIIe siècle',
    'Empire',
    'Restauration',
    'Second Empire',
    'Louis Philippe',
    'Louis XIV',
    'Louis XV',
    'Régence',
    'Directoire',
    'XVIe siècle',
    'XIXe siècle',
    'Paléolithique',
    'Louis XVIII',
    'Consulat',
    'Charles X',
    'Antique',
    'Art Déco',
    'Années 70',
    'Années 50',
  ];
  property: string[] = ['Propriété', 'Dépôt'];
  style: string[] = [
    'Baroque',
    'Rustique',
    'Néanderthal',
    'Empire',
    'Art Déco',
    'Louis XV',
    'Directoire',
    'Régence',
    'Restauration',
    'Napoléan III',
    'Transition',
    'Louis-Philippe',
    'Charles X',
    'Louis XIV',
    'Oriental',
    'Chinois',
    'Contemporain',
  ];
  oeuvres = [
    {
      id: 0,
      titre: 'Vénus de Milo',
      auteur: 'auteur',
      description: 'Une statue en marbre représentantla déesse Aphrodite-C.',
      mots_descriptifs: 'mots_descriptifs',
      commentaire: 'commentaire',
      image: 'assets/images/573.jpg',
      vip: 'true',
      domaine: 'Sculpture',
      editeur: "Alexandros d'Antioche",
      anneeCreation: 1820,
      dimension: '202x36x64',
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '12/07/1985',
      property: 'Propriété',
    },
    {
      id: 1,
      titre: 'La Joconde',
      description: 'Le Portrait de Mona Lisa est celui de la Florentine Lisa Gherardini',
      image: 'assets/images/1.jpg',
      vip: 'true',
      status: 'notRecieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1519,
      dimension: '77 × 53 cm',
      style: 'Renaissance',
      matiere: 'Huile sur panneau de bois',
      creationDate: '15/02/1975',
      property: 'Propriété',
    },
    {
      id: 2,
      titre: 'La Belle Ferronnière',
      description: 'Un tableau peint sur un panneau en bois de noyer',
      image: 'assets/images/2.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1497,
      dimension: '62 × 44 cm',
      style: 'Renaissance',
      matiere: 'Huile sur panneau de bois',
      creationDate: '30/11/1920',
      property: 'Propriété',
    },
    {
      id: 3,
      titre: 'La Liberté guidant le peuple',
      description: "Une huile sur toile d'Eugène Delacroix  ",
      image: 'assets/images/4.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Sculpture',
      editeur: 'Eugène Delacroix',
      anneeCreation: 1830,
      dimension: '260 × 325 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '25/12/1921',
      property: 'Dépôt',
    },
    {
      id: 4,
      titre: 'ECOLE FRANCAISE VERS 1830,D’APRÈS PIERRE...',
      description: 'ECOLE FRANCAISE VERS 1830, D’APRÈS PIERRE...',
      image: 'assets/images/25.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: '',
      anneeCreation: '',
      dimension: '77 × 53 cm',
      style: 'Tableau non classés',
      creationDate: '24/10/1919',
      property: 'Propriété',
    },
    {
      id: 5,
      titre: 'Victoire de Samothrace',
      description: "Un monument de sculpture grecque trouvé dans l'île de Samothrace.",
      image: 'assets/images/35.jpg',
      vip: 'false',
      status: 'notRecieved',
      domaine: 'Sculpture',
      anneeCreation: 1863,
      dimension: '77 × 53 cm',
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '30/11/1920',
      property: 'Dépôt',
    },
    {
      id: 6,
      titre: "L'Esclave mourant",
      auteur: 'auteur',
      description: 'Une statue en marbre représentantla déesse Aphrodite-C.',
      mots_descriptifs: 'mots_descriptifs',
      commentaire: 'commentaire',
      image: 'assets/images/162.JPG',
      vip: 'true',
      domaine: 'Sculpture',
      editeur: 'Michel-Ange',
      anneeCreation: 1820,
      dimension: '202x36x64',
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '27/09/1914',
      property: 'Propriété',
    },

    {
      id: 7,
      titre: 'La Vierge aux rochers',
      description: 'Considérée par les historiens comme la première des deux versions.',
      image: 'assets/images/0000.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1483,
      dimension: '199 × 122 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '30/11/1920',
      property: 'Dépôt',
    },
    {
      id: 8,
      titre: 'Les Noces de Cana',
      description: "Une huile sur toile d'Eugène Delacroix  ",
      image: 'assets/images/304.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Paul Véronèse',
      anneeCreation: 1563,
      dimension: '677 × 994 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '19/01/1990',
      property: 'Propriété',
    },
    {
      id: 9,
      titre: 'Victoire de Samothrace',
      description: "Un monument de sculpture grecque trouvé dans l'île de Samothrace.",
      image: 'assets/images/343 .jpg',
      vip: 'false',
      status: 'notRecieved',
      domaine: 'Sculpture',
      editeur: '',
      anneeCreation: 1863,
      dimension: '77 × 53 cm',
      matiere: 'Marbre',
      style: 'Sculpture',
      creationDate: '30/11/1920',
      property: 'Dépôt',
    },
    {
      id: 10,
      titre: "Vénus d'Arles",
      description: 'une sculpture en marbre dégagée en 1651',
      image: 'assets/images/365.jpg',
      vip: 'false',
      status: 'notRecieved',
      domaine: 'Sculpture',
      editeur: '',
      dimension: '194 cm (hauteur)',
      anneeCreation: 1651,
      matiere: 'Marbre',
      style: 'Tableau non classés',
      creationDate: '21/02/1920',
      property: 'Dépôt',
    },
    {
      id: 11,
      titre: 'Saint Jean-Baptiste',
      description: ' Peint sur une planche de noyer et mesure 69 × 57 cm',
      image: 'assets/images/12.jpg',
      vip: 'false',
      status: 'recieved',
      domaine: 'Peinture',
      editeur: 'Léonard de Vinci',
      anneeCreation: 1516,
      dimension: '69 × 57 cm',
      matiere: 'Huile sur panneau de bois',
      style: 'Renaissance',
      creationDate: '30/11/1920',
      property: 'Propriété',
    },
  ];

  constructor() {}
}
